version: '2.1'

services:
  server:
    image: server
    build: .
    environment:
      NODE_ENV: debug
      MONGO_URL: mongodb://mongo:27017/ignite2018
    ports:
      - 3001:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"      